pipeline {
    agent any
    
    tools {
    jdk 'jdk17'
    maven 'maven3'
}
    
    environment {
        SCANNER_HOME = tool 'sonar-scanner'
    }

    stages {
        stage('Git Checkout') {
            steps {
               git branch: 'master', credentialsId: 'git-cred', url: 'https://github.com/srj-103096/DevOps-Projects.git'
            }
        }
        stage('Compile') {
            steps {
                dir('DevOps-Project-38/FullStack-Blogging-App'){
                sh '''
                echo "===== Maven Version ====="
                mvn -version

                echo "===== Java Version ====="
                java -version

                echo "===== Compile ====="
                mvn compile
            '''
            }
        }
        }
        
        stage('Test') {
            steps {dir('DevOps-Project-38/FullStack-Blogging-App') {
            sh 'mvn test'
                sh "mvn test"
            }
        }
        }
        
        stage('File System Scan') {
            steps {
                dir('DevOps-Project-38/FullStack-Blogging-App') {
            sh '''
                mvn dependency:resolve
                trivy fs --format table -o trivy-fs-report.html .
            '''
        }
            }
        }
        stage('SonarQube Analsyis') {
            steps {
                withSonarQubeEnv('sonar') {
                    sh ''' $SCANNER_HOME/bin/sonar-scanner -Dsonar.projectName=bloggingapp -Dsonar.projectKey=bloggingapp \
                            -Dsonar.java.binaries=. '''
                }
            }
        }
        stage('Quality Gate') {
            steps {
                echo 'Skipping SonarQube Quality Gate check'
            }
        }
        stage('Build') {
            steps {
                dir('DevOps-Project-38/FullStack-Blogging-App') {
            sh 'mvn test'
                sh "mvn package"
                }
            }
        }
        stage('Publish To Nexus') {
            steps {
           dir('DevOps-Project-38/FullStack-Blogging-App') {

            withCredentials([
                usernamePassword(
                    credentialsId: 'nexus-cred',
                    usernameVariable: 'NEXUS_USERNAME',
                    passwordVariable: 'NEXUS_PASSWORD'
                )
            ]) {

                withMaven(
                    maven: 'maven3',
                    mavenSettingsConfig: 'global-settings'
                ) {
                    sh 'mvn deploy'
                }
                }
                }
            }
        }
        stage('Build & Tag Docker Image') {
    steps {
        dir('DevOps-Project-38/FullStack-Blogging-App') {
            withCredentials([
                usernamePassword(
                    credentialsId: 'docker-cred',
                    usernameVariable: 'DOCKER_USERNAME',
                    passwordVariable: 'DOCKER_PASSWORD'
                )
            ]) {
                sh '''
                    set -e

                    echo "$DOCKER_PASSWORD" | /usr/bin/docker login \
                        --username "$DOCKER_USERNAME" \
                        --password-stdin

                    /usr/bin/docker build \
                        -t abrahimcse/bloggingapp:latest \
                        .

                    /usr/bin/docker images | grep bloggingapp
                '''
            }
        }
    }
}

stage('Docker Image Scan') {
    steps {
        dir('DevOps-Project-38/FullStack-Blogging-App') {
            sh '''
                set -e

                trivy image \
                    --scanners vuln \
                    --format table \
                    -o trivy-image-report.html \
                    abrahimcse/bloggingapp:latest
            '''
        }
    }
}
        stage('Push Docker Image') {
            steps {
        withCredentials([
            usernamePassword(
                credentialsId: 'docker-cred',
                usernameVariable: 'DOCKER_USERNAME',
                passwordVariable: 'DOCKER_PASSWORD'
            )
        ]) {
            sh '''
                set -e

                echo "$DOCKER_PASSWORD" | /usr/bin/docker login \
                    --username "$DOCKER_USERNAME" \
                    --password-stdin

                /usr/bin/docker push abrahimcse/bloggingapp:latest

                /usr/bin/docker logout
            '''
               }
            }
        }
        stage('Deploy To Kubernetes') {
            steps {
                withKubeConfig(caCertificate: '', clusterName: 'abrahimcse-cluster', contextName: '', credentialsId: 'k8-cred', namespace: 'webapps', restrictKubeConfigAccess: false, serverUrl: 'https://< >.ap-southes-1.eks.amazonaws.com') {
                      sh "kubectl apply -f deployment-service.yaml"
                }
            }
        }
        
        stage('Verify the Deployment') {
            steps {
                withKubeConfig(caCertificate: '', clusterName: 'abrahimcse-cluster', contextName: '', credentialsId: 'k8-cred', namespace: 'webapps', restrictKubeConfigAccess: false, serverUrl: 'https://< >.ap-southes-1.eks.amazonaws.com') {
                        sh "kubectl get pods -n webapps"
                        sh "kubectl get svc -n webapps"
                }
            }
        }
    }

    post {
    always {
        script {
            def jobName = env.JOB_NAME
            def buildNumber = env.BUILD_NUMBER
            def pipelineStatus = currentBuild.result ?: 'UNKNOWN'
            def bannerColor = pipelineStatus.toUpperCase() == 'SUCCESS' ? 'green' : 'red'

            def body = """
                <html>
                <body>
                <div style="border: 4px solid ${bannerColor}; padding: 10px;">
                <h2>${jobName} - Build ${buildNumber}</h2>
                <div style="background-color: ${bannerColor}; padding: 10px;">
                <h3 style="color: white;">Pipeline Status: ${pipelineStatus.toUpperCase()}</h3>
                </div>
                <p>Check the <a href="${BUILD_URL}">console output</a>.</p>
                </div>
                </body>
                </html>
            """

            emailext (
                subject: "${jobName} - Build ${buildNumber} - ${pipelineStatus.toUpperCase()}",
                body: body,
                to: 'abrahim.ctech@gmail.com',
                from: 'jenkins@example.com',
                replyTo: 'jenkins@example.com',
                mimeType: 'text/html',
                attachmentsPattern: 'trivy-image-report.html'
            )
        }
      }       
    }   
}
